### PR TITLE
add template based on astropy proposal for enhancement template

### PR DESCRIPTION
**Pull request by kbarbary**
cc: @djperrefort @kboone @gnarayan @benjaminrose
Feel free to tag anyone else who might be interested.

### CODE REVIEW

**Comment by benjaminrose** [comment]
Should this be split into the README and an [Issues or Pull Request template](https://github.blog/2016-02-17-issue-and-pull-request-templates/)? So the README has the what and why, and the template has the structure?

**Comment by kbarbary** [comment]
Yes, I think a separate to-do here is to write a readme. (The astropy-APEs
readme is probably a good example to follow for the what and why.)

I believe issue and PR templates auto-populate the *description* of the
issue or PR, whereas we have a template for the *contents* of a PR.

>

**Comment by djperrefort** [comment]
@kbarbary I'm curious as to the workflow model. Are new SEP's to be submitted as PR's and then merging or closing them is equivalent to accepting/declining them? If so I second @benjaminrose's suggestion. Having a PR template makes the workflow intuitive and submitters can always choose to not use the template. I haven't set up PR templates before, but when adding issue templates there is a link that allows the submitter to not use a template at all.

**Comment by benjaminrose** [comment]
@djperrefort, the [JOSS review](https://github.com/openjournals/joss-reviews/issues) system works well. It all happens in Issues. First an issue to find reviewers then a separate issue for the review process.

**Comment by benjaminrose** [comment]
@kbarbary, it looks like there is both. An issue template (under the repo's settings) can automatically set metadata like labels, and assignees. But there is also a template file (stored in `.github/PULL_REQUEST_TEMPLATE.md`) that auto populates the body of the PR or Issue.

**Comment by rbiswas4** [comment]
Q: Is this for pushing things up to sncosmo only, or also about DESC updates and packages that will be based on sncosmo ?

**Comment by djperrefort** [comment]
I think in principle SEP’s should be sncosmo focused. Just as when writing code, writing an enhancement protocol should obey some principles of abstraction and isolation.

**Comment by kbarbary** [comment]
I think there's not a 1:1 relation between accepting/rejecting a proposal
and merging/closing a PR. For example, we might merge the PR, but reject
the proposal (so that we have a record of the proposal and the reason it
was rejected). The idea is that every clearly articulated proposal will be
eventually merged into the repo, but not all will necessarily be accepted.

Also, if you look at the astropy-APEs repo, there are many PRs that modify
an existing proposal.

That leaves open the question: when do we merge a PR containing a new
proposal and what does it mean when we do? The answer isn't obvious to me.
How about: After discussion has concluded and we have either decided to
accept or reject the proposal, OR if discussion had stalled or the proposal
is in limbo for some other reason, we can mark it as "status: Discussion"
and merge it, possibly to be picked up at a later date.

**Comment by kbarbary** [comment]
The JOSS review workflow works for JOSS but I think our use case might be a
bit different here.

One other thing: having the proposal in the pull request contents allows
reviewers to use github to comment on specific lines of the proposal. We
couldn't do that as easily if the proposal is in the PR description.

**Comment by benjaminrose** [comment]
I am seeing the limit of templates now. Yes, I agree that the templated enhancement proposal should be in the contents (via commits) of the PR not the conversation.

**Comment by benjaminrose** [comment]
Looking at [astropy](https://github.com/astropy/astropy-APEs) as a template system, I support merging this template file, and start to work on describing the process in the README.

**Comment by kbarbary** [comment]
@benjaminrose do you want to do the README?

**Pull request merged**
